/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Color;
import java.awt.Graphics2D;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author yeyo_
 */
public class Frm_Registrar_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Usuarios
     */
     private Webcam webcam;
     private WebcamPanel webcamPanel;
     
    
    
    
    public Frm_Registrar_Usuarios() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
     private void initWebcam() {
    webcam = Webcam.getDefault(); // Obtiene la webcam predeterminada
    if (webcam != null) {
        webcam.setViewSize(WebcamResolution.VGA.getSize()); // Establece la resolución de la webcam
        webcam.open(); // Abre la cámara

        // Crear un hilo para actualizar la imagen en el JLabel
        new VideoFeedUpdater().start();

    } else {
        JOptionPane.showMessageDialog(this, "No se encontró la cámara");
    }
}

// Clase interna para actualizar el JLabel con las imágenes de la webcam
private class VideoFeedUpdater extends Thread {
    @Override
    public void run() {
        while (webcam.isOpen()) {
            // Captura la imagen de la webcam
            BufferedImage image = webcam.getImage();
            
            if (image != null) {
                // Escalar la imagen a las dimensiones del JLabel
                ImageIcon icon = new ImageIcon(image.getScaledInstance(
                    jLabel_Foto_registro_1.getWidth(), 
                    jLabel_Foto_registro_1.getHeight(), 
                    Image.SCALE_SMOOTH));

                // Actualizar el JLabel con la imagen escalada
                jLabel_Foto_registro_1.setIcon(icon);
            }

            try {
                // Actualizar cada 30 ms aproximadamente (33 FPS)
                Thread.sleep(30);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
    
    

     public byte[] imageToByteArray(BufferedImage image) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            ImageIO.write(image, "jpg", baos); // Convertir la imagen a formato JPG o PNG
            return baos.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
     
     public BufferedImage convertToBufferedImage(Image img) {
    if (img instanceof BufferedImage) {
        return (BufferedImage) img;
    }

    // Crea un BufferedImage con las mismas dimensiones que la imagen original
    BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_RGB);

    // Dibuja la imagen en el BufferedImage
    Graphics2D bGr = bimage.createGraphics();
    bGr.drawImage(img, 0, 0, null);
    bGr.dispose();

    return bimage;
}
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Nombre_Usuario = new javax.swing.JTextField();
        jTextField_Aplellido_Usuario = new javax.swing.JTextField();
        jTextField_Tipo_Documento = new javax.swing.JTextField();
        jTextField_Numero_Documento_Usuario = new javax.swing.JTextField();
        jTextField_Correo_Electronico = new javax.swing.JTextField();
        jTextField_Telefono_Usuario = new javax.swing.JTextField();
        jTextField_Direccion_Usuario = new javax.swing.JTextField();
        jTextField_Ciudad_Residencia_Usuario = new javax.swing.JTextField();
        jButton_Registar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Confirmar_Correo = new javax.swing.JTextField();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();
        jPasswordField_Confirmar_Contraseña = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_Foto_registro_1 = new javax.swing.JLabel();
        jButton_Abrir_camara_1 = new javax.swing.JButton();
        jButton_Tomar_foto_1 = new javax.swing.JButton();
        jLabel_YaTengoCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 158, 255), 5, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 158, 255));
        jLabel1.setText("REGISTRAR USUARIOS");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Tipo documento");

        jLabel5.setText("Numero documento");

        jLabel6.setText("Correo electronico");

        jLabel7.setText("Telefono");

        jLabel8.setText("Direccion");

        jLabel9.setText("Ciudad residencia");

        jButton_Registar.setText("Registar");
        jButton_Registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistarActionPerformed(evt);
            }
        });

        jLabel10.setText("Confirmar correo");

        jPasswordField_Contraseña.setText("jPasswordField1");

        jPasswordField_Confirmar_Contraseña.setText("jPasswordField2");

        jLabel11.setText("Contraseña");

        jLabel12.setText("Confirmar contraseña");

        jLabel_Foto_registro_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 158, 255), 3, true));

        jButton_Abrir_camara_1.setText("Abrir camara");
        jButton_Abrir_camara_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Abrir_camara_1ActionPerformed(evt);
            }
        });

        jButton_Tomar_foto_1.setText("Tomar foto");
        jButton_Tomar_foto_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tomar_foto_1ActionPerformed(evt);
            }
        });

        jLabel_YaTengoCuenta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel_YaTengoCuenta.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jLabel_YaTengoCuenta.setText("Ya tengo una cuenta");
        jLabel_YaTengoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_YaTengoCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_YaTengoCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_YaTengoCuentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Abrir_camara_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Tomar_foto_1))
                            .addComponent(jLabel_Foto_registro_1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jButton_Registar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jTextField_Nombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Aplellido_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jTextField_Numero_Documento_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_Direccion_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_Telefono_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(55, 55, 55))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12))
                                            .addGap(11, 11, 11)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPasswordField_Confirmar_Contraseña)
                                        .addComponent(jPasswordField_Contraseña)
                                        .addComponent(jTextField_Correo_Electronico)
                                        .addComponent(jTextField_Confirmar_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField_Ciudad_Residencia_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel_YaTengoCuenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jTextField_Nombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jTextField_Aplellido_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jTextField_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(jTextField_Numero_Documento_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Correo_Electronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_Confirmar_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_Confirmar_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Telefono_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Direccion_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Ciudad_Residencia_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Foto_registro_1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Abrir_camara_1)
                    .addComponent(jButton_Tomar_foto_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Registar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_YaTengoCuenta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistarActionPerformed
        // TODO add your handling code here:

    String Fname = jTextField_Nombre_Usuario.getText();
    String Lname = jTextField_Aplellido_Usuario.getText();
    String pass1 = new String(jPasswordField_Contraseña.getPassword());
    String phone = jTextField_Telefono_Usuario.getText();
    String dirc = jTextField_Direccion_Usuario.getText();
    String mail = jTextField_Correo_Electronico.getText();
    String IdNumber = jTextField_Numero_Documento_Usuario.getText();

    // Validar que todos los campos estén completos
    if (IdNumber.isEmpty() || Fname.isEmpty() || Lname.isEmpty() || pass1.isEmpty() || phone.isEmpty() || dirc.isEmpty() || mail.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos deben ser completados");
        return;
    }

    try {
        // Encriptación usando SHA-256 para la contraseña
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        byte[] hashBytes = digest.digest(pass1.getBytes("UTF-8"));
        StringBuilder sb = new StringBuilder();
        for (byte b : hashBytes) {
            sb.append(String.format("%02x", b));
        }
        String sha256 = sb.toString();

        // Obtener la imagen del JLabel y convertirla a un arreglo de bytes
        ImageIcon icon = (ImageIcon) jLabel_Foto_registro_1.getIcon();
        if (icon != null) {
            Image image = icon.getImage();
            BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
            Graphics2D bGr = bufferedImage.createGraphics();
            bGr.drawImage(image, 0, 0, null);
            bGr.dispose();
            byte[] foto = imageToByteArray(bufferedImage); // Usar el método para convertir la imagen a bytes

            // Crear un nuevo objeto usuario con la foto incluida
            Controlador.Users usuario = new Controlador.Users(
                null, Fname, Lname, IdNumber, mail, sha256, phone, dirc, null, null, null, null, null, "activo", foto
            );

            // Insertar el usuario en la base de datos
            Controlador.Users.insertUser(usuario);
            JOptionPane.showMessageDialog(null, "Datos Insertados Correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna imagen.");
        }
    } catch (HeadlessException | UnsupportedEncodingException | NoSuchAlgorithmException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al insertar los datos: " + ex.getMessage());
    }
        
        
    }//GEN-LAST:event_jButton_RegistarActionPerformed

    private void jButton_Tomar_foto_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tomar_foto_1ActionPerformed
        // TODO add your handling code here:
         BufferedImage imagenCapturada = webcam.getImage(); // Captura la imagen
    if (imagenCapturada != null) {
        // Escalar la imagen capturada al tamaño del jLabel_Foto_registro
        Image imagenEscalada = imagenCapturada.getScaledInstance(
                jLabel_Foto_registro_1.getWidth(), // Ancho del JLabel
                jLabel_Foto_registro_1.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH); // Suaviza la escala de la imagen

        // Muestra la imagen escalada en el jLabel_Foto_registro
        ImageIcon icono = new ImageIcon(imagenEscalada);
        jLabel_Foto_registro_1.setIcon(icono);
        jLabel_Foto_registro_1.repaint(); // Actualiza el JLabel para mostrar la nueva imagen

        // Cierra la cámara
        webcam.close();
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró ninguna cámara.");
    } 
    }//GEN-LAST:event_jButton_Tomar_foto_1ActionPerformed

    private void jButton_Abrir_camara_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Abrir_camara_1ActionPerformed

        // TODO add your handling code here:
        initWebcam();
        Webcam webcam = Webcam.getDefault(); // Obtiene la cámara por defecto
        if (webcam != null) {
            webcam.open(); // Abre la cámara
        }
    }//GEN-LAST:event_jButton_Abrir_camara_1ActionPerformed

    private void jLabel_YaTengoCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_YaTengoCuentaMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.green);
        jLabel_YaTengoCuenta.setBorder(label_border);
    }//GEN-LAST:event_jLabel_YaTengoCuentaMouseEntered

    private void jLabel_YaTengoCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_YaTengoCuentaMouseExited
        Border label_create_accont_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        jLabel_YaTengoCuenta.setBorder(label_create_accont_border);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_YaTengoCuentaMouseExited

    private void jLabel_YaTengoCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_YaTengoCuentaMouseClicked
Vista.Frm_Inicio_Sesion rf = new Vista.Frm_Inicio_Sesion();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_YaTengoCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_Registrar_Usuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Abrir_camara_1;
    private javax.swing.JButton jButton_Registar;
    private javax.swing.JButton jButton_Tomar_foto_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Foto_registro_1;
    private javax.swing.JLabel jLabel_YaTengoCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Confirmar_Contraseña;
    private javax.swing.JPasswordField jPasswordField_Contraseña;
    private javax.swing.JTextField jTextField_Aplellido_Usuario;
    private javax.swing.JTextField jTextField_Ciudad_Residencia_Usuario;
    private javax.swing.JTextField jTextField_Confirmar_Correo;
    private javax.swing.JTextField jTextField_Correo_Electronico;
    private javax.swing.JTextField jTextField_Direccion_Usuario;
    private javax.swing.JTextField jTextField_Nombre_Usuario;
    private javax.swing.JTextField jTextField_Numero_Documento_Usuario;
    private javax.swing.JTextField jTextField_Telefono_Usuario;
    private javax.swing.JTextField jTextField_Tipo_Documento;
    // End of variables declaration//GEN-END:variables
}
