/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.Metodos;
import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;



/**
 *
 * @author yeyo_
 */
public final class Frm_Inicio_Sesion extends javax.swing.JFrame {

  
    /**
     * Creates new form Inicio_Sesion
     */
    public Frm_Inicio_Sesion() {
        initComponents();
        
        // create border for the username and password field
        
    
        
        this.setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    // Esperar a que los componentes se hayan renderizado para asegurarse de que el tamaño del JLabel esté disponible
    
    javax.swing.SwingUtilities.invokeLater(() -> {
        Metodos.CargarImagen_JLabel(jLabel_Logo, "src\\Vista\\Imagenes\\logo2.png");
    });
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Usuario = new javax.swing.JTextField();
        jLabel_Registrarse = new javax.swing.JLabel();
        jButton_Iniciar_Sesion = new javax.swing.JButton();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 158, 255), 5, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true)));

        jLabel_Logo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true), null));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 158, 255));
        jLabel1.setText("INCIO DE SESION");

        jTextField_Usuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextField_Usuario.setForeground(new java.awt.Color(0, 158, 255));
        jTextField_Usuario.setText("USUARIO");
        jTextField_Usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jTextField_Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsuarioFocusLost(evt);
            }
        });
        jTextField_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsuarioActionPerformed(evt);
            }
        });

        jLabel_Registrarse.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel_Registrarse.setForeground(new java.awt.Color(255, 0, 26));
        jLabel_Registrarse.setText("Crear una cuenta");
        jLabel_Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RegistrarseMouseExited(evt);
            }
        });

        jButton_Iniciar_Sesion.setText("INICIAR SESION");
        jButton_Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Iniciar_SesionActionPerformed(evt);
            }
        });

        jPasswordField_Contraseña.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jPasswordField_Contraseña.setForeground(new java.awt.Color(0, 158, 255));
        jPasswordField_Contraseña.setText("contraseña");
        jPasswordField_Contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_ContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_ContraseñaFocusLost(evt);
            }
        });
        jPasswordField_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_ContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Registrarse)
                            .addComponent(jButton_Iniciar_Sesion)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jPasswordField_Contraseña)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton_Iniciar_Sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Registrarse)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Iniciar_SesionActionPerformed
        PreparedStatement st;
        ResultSet rs;
    
    // Obtener el nombre de usuario y la contraseña ingresados
    String username = jTextField_Usuario.getText();  
    String password = String.valueOf(jPasswordField_Contraseña.getPassword());

    // Encriptar la contraseña
    String sha256 = "";
    try {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        digest.reset();
        digest.update(password.getBytes("utf8"));
        sha256 = String.format("%040x", new BigInteger(1, digest.digest()));
    } catch (UnsupportedEncodingException | NoSuchAlgorithmException e) {
        e.printStackTrace();
    }

    try {
        // Crear la consulta SQL para verificar si el nombre de usuario y la contraseña existen en la base de datos
        st = modelo.Conexion.getConnection().prepareStatement(
            "SELECT `nombre_usuario`, `contrasena_usuario` FROM `usuarios` WHERE `nombre_usuario` = ? AND `contrasena_usuario` = ?");
        
        // Verificar si los campos de nombre de usuario y contraseña están vacíos
        if (username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", JOptionPane.WARNING_MESSAGE);
        } else if (password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", JOptionPane.WARNING_MESSAGE);
        } else {
            // Establecer los parámetros de la consulta
            st.setString(1, username);
            st.setString(2, sha256);
            rs = st.executeQuery();

            // Si se encuentra el usuario y la contraseña en la base de datos
            if (rs.next()) {
                // Mostrar el formulario principal
                Vista.Frm_Menu rf = new Vista.Frm_Menu();
                 rf.setVisible(true);
                rf.pack();
                rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
                 
            } else {
                // Mostrar un mensaje de error si el nombre de usuario o la contraseña son incorrectos
                JOptionPane.showMessageDialog(null, "Invalid Username / Password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(Frm_Inicio_Sesion.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_jButton_Iniciar_SesionActionPerformed

    private void jLabel_RegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistrarseMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
        jLabel_Registrarse.setBorder(label_border);
    }//GEN-LAST:event_jLabel_RegistrarseMouseEntered

    private void jLabel_RegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistrarseMouseExited
        // TODO add your handling code here:
        Border label_create_accont_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        jLabel_Registrarse.setBorder(label_create_accont_border);
    }//GEN-LAST:event_jLabel_RegistrarseMouseExited

    private void jTextField_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsuarioActionPerformed

    private void jTextField_UsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsuarioFocusGained
        // TODO add your handling code here:
        if(jTextField_Usuario.getText().trim().toLowerCase().equals("USUARIO"))
        {
        } else {
            jTextField_Usuario.setText("");
            jTextField_Usuario.setForeground(Color.black);
        }
        
     
    }//GEN-LAST:event_jTextField_UsuarioFocusGained

    private void jTextField_UsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsuarioFocusLost
if(jTextField_Usuario.getText().trim().equals("") || 
           jTextField_Usuario.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_Usuario.setText("USUARIO");
            jTextField_Usuario.setForeground(new Color(0,158,255));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsuarioFocusLost

    private void jLabel_RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistrarseMouseClicked
        // TODO add your handling code here:
        Vista.Frm_Registrar_Usuarios rf = new Vista.Frm_Registrar_Usuarios();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_RegistrarseMouseClicked

    private void jPasswordField_ContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ContraseñaFocusGained
        // TODO add your handling code here:
       String pass = String.valueOf(jPasswordField_Contraseña.getPassword());
    
    // Verificar si el texto es "Contraseña" (ignorar mayúsculas y minúsculas)
    if (pass.trim().toLowerCase().equals("contraseña".toLowerCase())) {
        // Limpiar el contenido del campo de contraseña
        jPasswordField_Contraseña.setText("");
        // Cambiar el color del texto a negro
        jPasswordField_Contraseña.setForeground(Color.black);
    }
        
        
    }//GEN-LAST:event_jPasswordField_ContraseñaFocusGained

    private void jPasswordField_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_ContraseñaActionPerformed

    }//GEN-LAST:event_jPasswordField_ContraseñaActionPerformed

    private void jPasswordField_ContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ContraseñaFocusLost
        // TODO add your handling code here:
       String pass = String.valueOf(jPasswordField_Contraseña.getPassword());
        
        if(pass.trim().equals("") || 
           pass.trim().toLowerCase().equals("Contraseña"))
        {
            jPasswordField_Contraseña.setText("Contraseña");
            jPasswordField_Contraseña.setForeground(new Color(0,158,255));
        }
        
        // create a border with the color of the parent jpanel for the icons label to remove the move
        
    }//GEN-LAST:event_jPasswordField_ContraseñaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_Inicio_Sesion().setVisible(true);
        });
    }
         
    
     
    
     
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Iniciar_Sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Registrarse;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_Contraseña;
    private javax.swing.JTextField jTextField_Usuario;
    // End of variables declaration//GEN-END:variables
}
